import Independent_Study.Main as Main

def test_product_json() :
    a = Main.brand_name_match('{"Brand":["Durabrand"],"Warranty Length":["3 Years"],"Country of Origin: Components":["Imported"],"Type":["Rechargeable Nickel Metal Hydride (NiMH)"],"Product Short Description":["Compatible with many Nikon CoolPix, Fuji FinePix and Olympus Stylus digital camera models"],"Product Segment":["Electronics"],"Battery Size":["Camera Battery"],"Product Name":["Battery Biz Duracell Camera battery for Kodak EasyShare C300 CX6000, CX7000, DX6300 Series"],"Product Type":["Device-Specific Electronics Batteries"],"Manufacturer Part Number":["DR9576"],"Category":["Batteries"],"Assembled Product Width":["1.1"],"Product Long Description":["Compatible with many Nikon CoolPix, Fuji FinePix and Olympus Stylus digital camera models"],"Assembled Product Length":["1.9"],"GTIN":["00609525749526"],"Assembled Product Height":["0.5"],"Composite Wood Code":["1"],"Warranty Information":["For all warranty items call 800-848-6782"],"UPC":["609525749526"]}',
                          '{"Product Type":["Device-Specific Electronics Batteries"],"Manufacturer Part Number":["DR9576"],"Product Name":["Battery Biz DR9576 Camera Battery for Kodak"],"Brand":["Battery Biz"],"Manufacturer":["Battery Biz"],"Product Long Description":["Duracell Camera battery - Kodak EasyShare C300 CX6000 CX7000 DX6300 Series...Compatible with many Nikon CoolPix Fuji FinePix and Olympus Stylus digital camera models; 100% OEM compatible; No memory effect; Rechargeable NiMH battery that will provide hundreds of shots; 2100mAh NiMH 2.4V."],"Item ID":["10629557"],"Product Segment":["Electronics"],"UPC":["609525749526"]}')
    print a
    a = Main.brand_name_match('{"Product Name":["APPLETON ELECTRIC TMC2X-050075A Cable Connector, 1/2 In, Straight, Silver"],"Product Type":["Cable Connectors"],"Manufacturer Part Number":["TMC2X-050075A"],"Product Long Description":["Hazardous Location Cable Connector, Conduit Size 1/2 In., Cord Dia. Range 0.50 to 0.75 In., Material Aluminum, Min. Throat Dia. 0.78 In., Connector Type Straight, Color Silver, Length 1.65 In., Standards UL 514B, UL 2225, CSA C22.2 No. 174, 249506; Class I, Division 2, Groups A, B, C, D; Class I, Zones 1 and 2, AExe II, AEx tA IIC; Class I, Zones 1 and 2, Exe II, Ex tA IIC; Class II, Divisions 1 and 2, Groups E, F, G; Class III, Divisions 1 and 2; NEMA 4X; IP66<br><b>Features</b><ul><li>Color : Silver</li><li>Conduit Size (In.) : 1/2</li><li>Connector Type : Straight</li><li>Cord Dia. (In.) : 0.50 to 0.75</li><li>Item : Hazardous Location Cable Connector</li><li>Length (In.) : 2.45</li><li>Material of Construction : Aluminum</li><li>Type : Hazardous Location, Explosionproof, Jacketed Metal Clad Cable</li><li>Min. Throat Dia. (In.) : 0.42</li><li>Standards : UL 514B, UL 2225, CSA C22.2 No. 174, 249506; Class I, Division 2, Groups A, B, C, D; Class I, Zones 1 and 2, AExe II, AEx tA IIC; Class I, Zones 1 and 2, Exe II, Ex tA IIC; Class II, Divisions 1 and 2, Groups E, F, G; Class III, Divisions 1 and 2; NEMA 4X; IP66</li><li>For Use With : Jacketed Metal Clad Cable</li><li>Length : 1.65</li><li>Material : Aluminum</li><li>Conduit Size : 1/2</li><li>Cord Dia. Range : 0.50 to 0.75</li><li>Min. Throat Dia. : 0.78</li></ul>"],"GTIN":["II59OLTCm35947"],"Product Short Description":["Cable Connector,1/2 In,Straight,Silver"],"Material":["Aluminum"],"UPC":["59OLTCm35947"],"Product Segment":["Electronics"]}',
                          '{"Product Type":["Cable Connectors"],"Product Name":["APPLETON ELECTRIC TMC2-125137NB Connector1.02 to 1.37 In Cable Dia"],"Product Long Description":["Hazardous Location Cable Connector Conduit Size 1-1/4 In. Cord Dia. Range 1.02 to 1.37 In. Material Nickel Plated Brass Min. Throat Dia. 1.00 In. Connector Type Straight Color Gold Length 2.34 In. Standards UL 514B UL 2225 CSA C22.2 No. 174 249506; Class I Division 2 Groups A B C D; Class I Zones 1 and 2 AExe II AEx tA IIC; Class I Zones 1 and 2 Exe II Ex tA IIC; Class II Divisions 1 and 2 Groups E F G; Class III Divisions 1 and 2; NEMA 4X; IP66<br><b>Features</b><ul><li>Color : Gold</li><li>Conduit Size (In.) : 1-1/4</li><li>Connector Type : Straight</li><li>Cord Dia. (In.) : 1.02 to 1.37</li><li>For Use With : Jacketed Metal Clad Cable</li><li>Item : Hazardous Location Cable Connector</li><li>Length : 2.34</li><li>Length (In.) : 3.34</li><li>Material : Nickel Plated Brass</li><li>Material of Construction : Nickel Plated Brass</li><li>Type : Hazardous Location Jacketed Metal Clad Cable</li><li>Min. Throat Dia. (In.) : 1.22</li><li>Standards : UL 514B UL 2225 CSA C22.2 No. 174 249506; Class I Division 2 Groups A B C D; Class I Zones 1 and 2 AExe II AEx tA IIC; Class I Zones 1 and 2 Exe II Ex tA IIC; Class II Divisions 1 and 2 Groups E F G; Class III Divisions 1 and 2; NEMA 4X; IP66</li><li>Conduit Size : 1-1/4</li><li>Cord Dia. Range : 1.02 to 1.37</li><li>Min. Throat Dia. : 1.00</li></ul>"],"Item ID":["41942061"],"Product Segment":["Electronics"],"UPC":["I57OLTCmz5934"]}',
                              'files/test_brand_dict.txt')
    print a


test_product_json()
